project:
  type: book

book:
  title: "Statistics with R"
  author: "Sharan S."
  date: "10/13/2022"
  chapters:
    - index.qmd
    - part: inferential-statistics.qmd
      chapters:
        - paired-t.qmd
        - two-sample-t.qmd
        - analysis-of-variance.qmd
  page-navigation: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
