project:
  type: book

book:
  title: "Statistics with R"
  author: "Sharan S."
  date: "10/13/2022"
  chapters:
    - index.qmd
    - part: descriptive-statistics/index.qmd
      chapters:
        - descriptive-statistics/making-graphs.qmd
        - descriptive-statistics/single-variable.qmd
        - descriptive-statistics/multiple-variables.qmd
    - part: inferential-statistics/index.qmd
      chapters:
        - inferential-statistics/paired-t.qmd
        - inferential-statistics/two-sample-t.qmd
        - inferential-statistics/analysis-of-variance.qmd
    - part: non-parametric/index.qmd
      chapters:
        - non-parametric/mann-whitney-u.qmd
        - non-parametric/kruskal-wallis.qmd
  page-navigation: false

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
